### ISSUE TITLE
Need help setting up if possible

### ISSUE THREAD

**Issue by xInstacart** [aesthetic0001/2Lazy2Flip#12]
I am like completely new to github , I'm not a coder or anything. I just need help setting up your 2lazy2flip project, I have literally 0 clue on what to do , Literally all I know is how to download the code...

**Comment by aesthetic0001** [comment]
You should start by installing nodejs 14+
Then once that's installed configure the config.json file 
Then on a command prompt, CD inside the folder, then type `npm i`
finally once that's done type `node start` and you should be set
This should be significantly simplified once it becomes an app
I'll make a video on the setup process sometime in the future

**Comment by xInstacart** [comment]
Ngl , im stuck on the 3rd step of "Then on a command prompt, CD inside the folder, then type npm i"

**Comment by aesthetic0001** [comment]
Open a command prompt or terminal instance (depends on ur os) then type CD Downloads then CD whatever the file name is

**Comment by xInstacart** [comment]
Im like struggling on trying to understand this third step ); a video would be insanely appreciated

**Comment by aesthetic0001** [comment]
yup this will be worked on

**Comment by aesthetic0001** [comment]
there's docs now, see https://github.com/aesthetic0001/2Lazy2Flip/tree/main/docs
